[tool.poetry]
name = "umdb"
version = "0.1.0"
description = ""
authors = ["Kirill Voronin <yoursdearboy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
sqlalchemy = "^2.0.29"
psycopg2-binary = "^2.9.9"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
ruff = "^0.5.5"
sqlalchemy-schemadisplay = "^2.0"
mkdocstrings = {extras = ["python"], version = "^0.25.2"}
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.30"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F403"]
